# Generated by Django 4.2.4 on 2023-08-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='right_answers',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='wrong_answers',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
